"""initial migration

Revision ID: a43bc84a5960
Revises: 
Create Date: 2023-11-28 11:38:37.008447

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a43bc84a5960'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('display_object',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('link', sa.String(length=150), nullable=True),
    sa.Column('display_name', sa.String(length=150), nullable=True),
    sa.Column('thumbnail', sa.String(length=150), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('order', sa.Integer(), nullable=True),
    sa.Column('display_type', sa.Integer(), nullable=True),
    sa.Column('owner', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('display_name', sa.String(length=150), nullable=True),
    sa.Column('password', sa.String(length=150), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    op.drop_table('display_object')
    # ### end Alembic commands ###
